# Generated by Django 4.2.25 on 2025-11-21 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0014_ltitool_launch_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('assignment', 'Assignment'), ('page', 'Page')], max_length=20)),
                ('content_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'canvas_app_explorer_content_item',
            },
        ),
        migrations.CreateModel(
            name='CourseScan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_id', models.BigIntegerField(unique=True)),
                ('q_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'canvas_app_explorer_course_scan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_id', models.BigIntegerField()),
                ('image_url', models.URLField(max_length=2048)),
                ('content_item', models.ForeignKey(db_column='content_item_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='canvas_app_explorer.contentitem')),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='image_items', to='canvas_app_explorer.coursescan', to_field='course_id')),
            ],
            options={
                'db_table': 'canvas_app_explorer_image_item',
            },
        ),
        migrations.AddField(
            model_name='contentitem',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='canvas_app_explorer.coursescan', to_field='course_id'),
        ),
    ]
