# Generated by Django 4.2.25 on 2025-11-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0014_ltitool_launch_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseScan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('canvas_id', models.BigIntegerField(db_index=True)),
                ('scan_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'canvas_app_explorer_course_scan',
                'ordering': ['-created_at'],
            },
        ),
    ]
