# Generated by Django 4.2.25 on 2025-11-19 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0015_coursescan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursescan',
            name='canvas_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_content_type', models.CharField(choices=[('assignment', 'Assignment'), ('page', 'Page')], max_length=20)),
                ('image_id', models.BigIntegerField()),
                ('image_url', models.URLField(max_length=2048)),
                ('image_content_id', models.BigIntegerField()),
                ('course_scan', models.ForeignKey(db_column='canvas_id', on_delete=django.db.models.deletion.CASCADE, related_name='image_items', to='canvas_app_explorer.coursescan', to_field='canvas_id')),
            ],
            options={
                'db_table': 'canvas_app_explorer_image_item',
            },
        ),
    ]
