# Generated by Django 4.2.27 on 2026-02-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0023_alter_coursescan_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolcategory',
            options={'verbose_name': 'Tool Category', 'verbose_name_plural': 'Tool Categories'},
        ),
    ]
