# Generated by Django 5.2.12 on 2026-04-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0024_alter_toolcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitem',
            name='content_item',
            field=models.BigIntegerField(db_column='content_id'),
        ),
    ]
