# Generated by Django 5.2.12 on 2026-04-08 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0026_imageitem_content_item_id_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageitem',
            name='content_item_fk',
        ),
    ]
