# Generated by Django 5.2.13 on 2026-04-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0026_remove_coursescan_q_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursescan',
            name='total_image_count',
            field=models.IntegerField(default=0),
        ),
    ]
