# Generated by Django 5.2.13 on 2026-05-06 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0027_coursescan_total_image_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseScanErrorLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('error_type', models.CharField(max_length=50)),
                ('error_message', models.TextField()),
                ('canvas_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_scan', models.ForeignKey(db_column='course_scan_id', on_delete=django.db.models.deletion.CASCADE, related_name='scan_errors', to='canvas_app_explorer.coursescan')),
            ],
            options={
                'db_table': 'canvas_app_explorer_course_scan_error_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course_scan', '-created_at'], name='canvas_app__course__01806d_idx')],
            },
        ),
    ]
