# Generated by Django 4.2 on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0028_coursescanerrorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursescanerrorlog',
            name='error_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
