# Generated by Django 5.2.12 on 2026-04-08 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0029_backfill_imageitem_content_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageitem',
            name='course',
        ),
    ]
