# Generated by Django 5.2.12 on 2026-04-08 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0030_remove_imageitem_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageitem',
            name='content_item',
        ),
    ]
