# Generated by Django 5.2.12 on 2026-04-08 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0031_remove_imageitem_content_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='course_scan',
            field=models.ForeignKey(blank=True, db_column='course_scan_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='canvas_app_explorer.coursescan'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='content_items_legacy', to='canvas_app_explorer.coursescan', to_field='course_id'),
        ),
    ]
