# Generated by Django 5.2.12 on 2026-04-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0033_backfill_contentitem_course_scan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentitem',
            name='course',
        ),
        migrations.AlterField(
            model_name='coursescan',
            name='course_id',
            field=models.BigIntegerField(),
        ),
    ]
