# Generated by Django 5.2.12 on 2026-04-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0034_remove_contentitem_course_alter_coursescan_course_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='imageitem',
                    name='content_item',
                    field=models.ForeignKey(
                        blank=True,
                        db_column='content_item_id',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='images',
                        to='canvas_app_explorer.contentitem',
                    ),
                ),
            ],
        ),
    ]
