# Generated by Django 5.2.12 on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0035_add_imageitem_content_item_fk'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "DELETE FROM canvas_app_explorer_image_item "
                "WHERE content_item_id IS NULL"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=(
                "DELETE FROM canvas_app_explorer_content_item "
                "WHERE course_scan_id IS NULL"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='content_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='course_scan',
            field=models.ForeignKey(
                db_column='course_scan_id',
                on_delete=models.deletion.CASCADE,
                related_name='content_items',
                to='canvas_app_explorer.coursescan',
            ),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='content_item',
            field=models.ForeignKey(
                db_column='content_item_id',
                on_delete=models.deletion.CASCADE,
                related_name='images',
                to='canvas_app_explorer.contentitem',
            ),
        ),
        migrations.AddConstraint(
            model_name='contentitem',
            constraint=models.UniqueConstraint(
                fields=('course_scan', 'content_id'),
                name='uniq_contentitem_scan_content_id',
            ),
        ),
    ]
